# Generated by Django 4.0.6 on 2022-08-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0004_midia_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pix',
            old_name='cpf',
            new_name='cnpj',
        ),
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='dt_entrega',
        ),
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='dth',
        ),
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='pedido2',
        ),
        migrations.RemoveField(
            model_name='pix',
            name='pix',
        ),
        migrations.AddField(
            model_name='itenscarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itenscarrinho',
            name='qnt_item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pix',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='boleto1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.boleto'),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='cartao1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.cartao'),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='pix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.pix'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
