# Generated by Django 4.0.6 on 2022-08-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0007_remove_boleto_boleto_boleto_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='banco',
        ),
    ]
