# Generated by Django 4.0.6 on 2022-08-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0008_remove_boleto_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='validade',
            field=models.DateField(),
        ),
    ]
