# Generated by Django 4.0.6 on 2022-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0009_alter_cartao_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='validade',
            field=models.DateField(verbose_name=['%m/%Y/']),
        ),
    ]
