# Generated by Django 4.0.6 on 2022-08-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0014_alter_cartao_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='validade',
            field=models.DateField(),
        ),
    ]
