# Generated by Django 4.0.6 on 2022-08-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0015_alter_cartao_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='dt_entrega',
        ),
    ]
