# Generated by Django 4.0.6 on 2022-08-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0016_remove_pedidocarrinho_dt_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario2',
        ),
        migrations.AddField(
            model_name='comentario',
            name='planta1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.usuario'),
            preserve_default=False,
        ),
    ]
