# Generated by Django 4.0.6 on 2022-08-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0017_remove_comentario_comentario1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario1',
            new_name='comentario1',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='planta1',
            new_name='comentario2',
        ),
    ]
