# Generated by Django 4.0.6 on 2022-08-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0018_rename_usuario1_comentario_comentario1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario2',
        ),
    ]
