# Generated by Django 4.0.6 on 2022-08-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0020_comentario_comentario1_comentario_comentario2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario2',
        ),
    ]
